Repository fermyon/developer, pull requests merged in 2023-07, with the labels that each got.

#731 Add Spin v 1.4 CLI Reference
  content/spin/cli-reference.md
Labels: hold_until_spin_1_4_0_release

#732 docs theme - visual update
  static/css/search-white.8e5bc66c.svg
  static/css/search.2af741de.svg
  static/css/styles.css
  static/image/fermyon-badge.png
  static/image/search-white.svg
  static/image/search.svg
  static/sass/developer-color-dark.scss
  static/sass/developer-color-light.scss
  static/sass/developer-color.scss
  static/sass/developer-content-home.scss
  static/sass/developer-include-footer.scss
  static/sass/developer-include-search.scss
  static/sass/developer-include-sidebar.scss
  static/sass/developer-include-topbar.scss
  static/sass/developer-responsive.scss
  static/sass/styles.scss
  templates/bartholomew_main.hbs
  templates/bartholomew_sidebar.hbs
  templates/changelog.hbs
  templates/changelog_item.hbs
  templates/cloud_main.hbs
  templates/cloud_sidebar.hbs
  templates/common_sidebar.hbs
  templates/content_bottom.hbs
  templates/content_footer.hbs
  templates/content_navbar.hbs
  templates/content_top.hbs
  templates/home.hbs
  templates/spin_main.hbs
  templates/spin_sidebar.hbs
Labels: design

#764 Karthik/spin up hub
  spin-up-hub/index.html
  spin-up-hub/public/static/image/gradient-blue-dark.jpg
  spin-up-hub/public/static/image/gradient-blue-green.jpg
  spin-up-hub/public/static/image/gradient-green-dark.jpg
  spin-up-hub/public/static/image/gradient-pink-blue.jpg
  spin-up-hub/public/static/image/gradient-pink-purple.jpg
  spin-up-hub/public/static/image/gradient-purple-dark.jpg
  spin-up-hub/public/static/image/icon-back.svg
  spin-up-hub/public/static/image/icon-close.svg
  spin-up-hub/public/static/image/icon-code.svg
  spin-up-hub/public/static/image/icon-external.svg
  spin-up-hub/public/static/image/icon-github.svg
  spin-up-hub/public/static/image/icon-search-dark.svg
  spin-up-hub/public/static/image/icon-search.svg
  spin-up-hub/public/static/image/spin.svg
  spin-up-hub/src/App.vue
  spin-up-hub/src/components/Card.vue
  spin-up-hub/src/components/ContentFilter.vue
  spin-up-hub/src/components/ContentListing.vue
  spin-up-hub/src/components/ContentSpace.vue
  spin-up-hub/src/components/HubIntro.vue
  spin-up-hub/src/components/PreviewModal.vue
  spin-up-hub/src/components/TopBar.vue
  spin-up-hub/src/view/Contributing.vue
  spin-up-hub/src/view/Home.vue
  templates/content_navbar.hbs
Labels: design

#751 Go HTTP template
  content/api/hub/template_http_go.md
Labels: doNotMergeYet

#752 Redis templates
  content/api/hub/template_redis_go.md
  content/api/hub/template_redis_rust.md
Labels: doNotMergeYet

#753 Dioxus and Like Button samples
  content/api/hub/dioxus.md
  content/api/hub/like-button.md
Labels: doNotMergeYet

#763 added static file server, todo, and other content
  content/api/hub/sample_todo.md
  content/api/hub/template_kv_explorer.md
  content/api/hub/template_nextjs.md
  content/api/hub/template_spin_fileserver.md
Labels: doNotMergeYet

#755 Added OpenAI Chat template
  content/api/hub/sample_openaichat_ts.md
Labels: doNotMergeYet

#740 Sqlite in cloud documentation
  content/cloud/faq.md
  content/cloud/fermyon-cloud.md
  content/cloud/noops-sql-db.md
  content/spin/api-guides-overview.md
  templates/cloud_sidebar.hbs
Labels: only-merge-at-UTC-2023-07-26T16:00:00Z

#758 Add Spin Cloud SQLite Reference (v0.1.2)
  content/cloud/cloud-command-reference.md
  content/spin/cli-reference.md
Labels: only-merge-at-UTC-2023-07-26T16:00:00Z

#760 Changelog: Create cloud-custom-domains.md
  content/cloud/changelog/cloud-custom-domains.md
Labels: only-merge-at-UTC-2023-07-26T16:00:00Z

#761 Changelog: Create cloud-noops-sql-db.md
  content/cloud/changelog/cloud-noops-sql-db.md
Labels: only-merge-at-UTC-2023-07-26T16:00:00Z
